// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrjpB8_Ixlz2NzVRAHShKAB1jxT_J-oiE',
    appId: '1:191103213609:web:bcf54cc8b8f08a4c9bfc38',
    messagingSenderId: '191103213609',
    projectId: 'lancer-ab3c5',
    authDomain: 'lancer-ab3c5.firebaseapp.com',
    storageBucket: 'lancer-ab3c5.appspot.com',
    measurementId: 'G-XX84RBSR5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDywoCl4U9O_bYVRIp4W8JD_hrUc0df9w',
    appId: '1:191103213609:android:016fb997ea07bd1a9bfc38',
    messagingSenderId: '191103213609',
    projectId: 'lancer-ab3c5',
    storageBucket: 'lancer-ab3c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWHj1yvW6R9wt9RcAeVQF_39Hftf6pUhg',
    appId: '1:191103213609:ios:e308a06840811b539bfc38',
    messagingSenderId: '191103213609',
    projectId: 'lancer-ab3c5',
    storageBucket: 'lancer-ab3c5.appspot.com',
    iosBundleId: 'com.example.lancer1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWHj1yvW6R9wt9RcAeVQF_39Hftf6pUhg',
    appId: '1:191103213609:ios:e308a06840811b539bfc38',
    messagingSenderId: '191103213609',
    projectId: 'lancer-ab3c5',
    storageBucket: 'lancer-ab3c5.appspot.com',
    iosBundleId: 'com.example.lancer1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrjpB8_Ixlz2NzVRAHShKAB1jxT_J-oiE',
    appId: '1:191103213609:web:1716e7158bed5cc89bfc38',
    messagingSenderId: '191103213609',
    projectId: 'lancer-ab3c5',
    authDomain: 'lancer-ab3c5.firebaseapp.com',
    storageBucket: 'lancer-ab3c5.appspot.com',
    measurementId: 'G-TVH3C458TY',
  );

}